name: Python Package and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      run: pip install uv

    - name: Sync dependencies
      run: uv sync

    - name: Test with pytest
      run: uv run pytest

    - name: Python Black
      run: uv run black . --check